name: privacyidea_authenticator
description: An OTP Authenticator App for privacyIDEA Authentication Server.
homepage: https://netknights.it
repository: https://github.com/privacyidea/pi-authenticator

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.12+0300012 # TODO Set the right version number
# version: major.minor.build          + 2x major|2x minor|3x build
# version: version number             + build number (optional)
# android: build-name                 + versionCode
# iOS    : CFBundleShortVersionString + CFBundleVersion

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  flutter_cupertino_localizations: ^1.0.1
  intl: ^0.17.0
  #  intl_translation: any #^0.17.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^0.1.2


  hex: ^0.2.0 # https://pub.dev/packages/hex#-installing-tab-
  uuid: ^3.0.1
  flutter_secure_storage: ^4.1.0
  json_annotation: ^4.0.0 # run "flutter pub run build_runner build" in terminal to build tokens.g.dart
  package_info: ^2.0.0 # https://pub.dev/packages/package_info
  http: ^0.13.0
  mutex: ^2.0.0
  flutter_markdown: ^0.6.0
  url_launcher: ^6.0.2
  local_auth: ^1.1.0


  ##### not null-safe:

  ## pre-release
#  base32: ^1.1.1 # https://pub.dev/packages/base32
  base32: ^2.0.0-nullsafety.1
#  otp: ^2.0.3 # https://pub.dev/packages/otp
  otp: ^3.0.0-nullsafety.0
  barcode_scan: ^2.0.1
#  flutter_slidable: ^0.5.4
  flutter_slidable: ^0.6.0-nullsafety.0
  pointycastle: ^1.0.2
  asn1lib: ^0.6.4
  flutter_local_notifications: ^1.4.1 # https://pub.dev/packages/flutter_local_notifications#-installing-tab-
  flutter_svg: ^0.19.1


  ## without pre-release
  streaming_shared_preferences: ^1.0.1
  flutterlifecyclehooks: ^1.0.1
  pi_authenticator_legacy:
    path: ./local_plugins/pi-authenticator-legacy



  ## unknown:

  #  dynamic_theme: ^1.0.1 # https://pub.dev/packages/dynamic_theme
  dynamic_theme:
    git:
      url: https://github.com/timosturm/dynamic_theme.git

  # firebase_messaging: ^6.0.9
  firebase_messaging:
    path: ./local_plugins/firebase_messaging-6.0.16

  firebase_core: ^0.4.0


# Overwrite because flutter driver depends on crypto <? and uuid depends on crypto >=3
dependency_overrides:
  crypto: ">=3.0.0"
  args: ">=2.0.0"




dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

  # dependencies to serialize objects to json
  build_runner: ^1.10.1  # null-safety unknown
  json_serializable: ^4.0.2  # null-safety unknown

#  intl_translation:
#    git:
#      url: https://github.com/timosturm/intl_translation.git


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/logo/app_logo_light.svg
    - CHANGELOG.md
    - res/md/GUIDE_de.md
    - res/md/GUIDE_en.md
    - res/gif/help_delete_rename.gif
    - res/gif/help_manual_poll.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages